spring:
  datasource:
    username: lldj
    password: lldj123414
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: da98f9f5a3a42cb1a2e41ebaee86cd3b
            scope:
            redirect-uri: http://localhost:9050/login/oauth2/code/kakao
          google:
            client_id: 794404975519-hadbu9kg1dpbiu0oqu7h6os2o33a4q0k.apps.googleusercontent.com
            client_secret: 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